### ISSUE TITLE
Memory

### ISSUE THREAD

**Issue by MartinBrugnara** [MartinBrugnara/archetypum#1]
Memory abstraction is required for _cache_ emulation, and for `LOAD` and `STORE` instructions.

Specs:
- Reading from uninitialized memory loc. returns random value
- Reading from a previously written memory loc. returns consistent value.

Plus:
- Memory latency is programmable

**Comment by GianlucaBortoli** [comment]
Memory instructions are like this:
- ```LDR <base>, <offset>, <destination_register>```
- ```STR <value>, <location>```
