### ISSUE TITLE
Not working with safari

### ISSUE THREAD

**Issue by GianlucaBortoli** [MartinBrugnara/archetypum#12]
Chrome & firefox are fine. Probably some ES6 feature isn't supported by safari.

**Comment by MartinBrugnara** [comment]
Safari is broken indeed: https://bugs.webkit.org/show_bug.cgi?id=148763.
The fix was release on 2016-07-01 ... let's wait for the stable release to catch up.

Alternative: do not use let + variable name that are equals to tag id.
