### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by MartinBrugnara** [MartinBrugnara/archetypum#2]
Once memory abstraction is in place #1 , add support for cache emulation.

Kind:
- [x] No cache
- [x] Decide which to should be implement.
       Once the interface is defined external contribution are really welcomed here (easy but meany possibilities)
- [x] n-way set associative (non concurrent)

**Comment by GianlucaBortoli** [comment]
Implementing write-back/write-through policies & random eviction protocol if cache is full
